### ISSUE TITLE
README.md - DDL Foreign Key의 ON UPDATE SET NULL, ON DELETE SET NULL 처리 

### ISSUE THREAD

**Issue by t4e1** [beyond-sw-camp/be04-1st-EarlyFar-FaaarCar#10]
# DDL Foreign Key의 ON UPDATE SET NULL, ON DELETE SET NULL 처리 

- [ ] ON DELETE SET NULL 추가 
- [ ] ON UPDATE SET NULL 추가

**Comment by CJC0512** [comment]
부모 테이블이 원만하게 삭제 되려면 해당 구문을 추가시켜야 될텐데 어떻게 생각하시나요?

**Comment by t4e1** [comment]
FK로 사용하던 컬럼에 NULL 값이 들어가면 의미 없는 데이터가 되지 않을까요?? 어떤 경우에 설정해야 할지 생각해봐야 할 것 같습니다.

**Comment by t4e1** [comment]
개인적으로는 저희가 참조하는 부모 테이블이 전부 Member_ID 나 Board_ID 등 삭제 되면 안되는 컬럼이 많기 때문에 오히려 삭제하려면 경고를 띄워주는게 더 나을 것 같긴 합니다.

**Comment by CJC0512** [comment]
확실히 저희가 부모 테이블을 제거할 때, Trigger를 사용해서 제거하는 것으로 설계하고 있으니, 해당 구문을 작성하지 않고 경고문으로 유도하는 것이 더 깔끔할 수 있겠네요.

**Comment by t4e1** [comment]
그럼 일단 해당 이슈는 클로즈 하는것으로 하겠습니다. 차후에 필요한 경우가 생기면 리오픈해서 추가하는걸로 하겠습니다

**Comment by dongjunsong** [comment]
넵 좋은 생각인거 같아요 제가 생각해도 경고문으로 유도해야지 안전할것같습니다!

**Comment by CJC0512** [comment]
다들 좋은 의견 감사합니다.
