### ISSUE TITLE
README.md - TESTCASE 결과 이미지 추가 

### ISSUE THREAD

**Issue by t4e1** [beyond-sw-camp/be04-1st-EarlyFar-FaaarCar#12]
# TESTCASE 결과 이미지 추가 

- [x] create database & table
- [x] insert data
- [x] TC-001
- [x] TC-002
- [x] TC-003
- [x] TC-004
- [x] TC-005
- [x] TC-006
- [x] TC-007
- [x] TC-008
- [x] TC-009
- [x] TC-010
- [x] 이미지 README.md에 추가

**Comment by t4e1** [comment]
담당한 gif 이미지 완성되면 번호 댓글 주시면 감사하겠습니다

**Comment by dongjunsong** [comment]
1번2번3번 gif 추가했습니다

**Comment by CJC0512** [comment]
보다 정확한 진행상황 파악을 위해, 체크박스 수정하였습니다. 확인 부탁드립니다.

**Comment by letsplaycoding** [comment]
**TEST 7,8,10번**  gif 업로드했습니다. 확인 부탁 드립니다.
