### ISSUE TITLE
README.md 이미지 업로드 오류

### ISSUE THREAD

**Issue by CJC0512** [beyond-sw-camp/be04-1st-EarlyFar-FaaarCar#3]
# README.md 이미지 업로드 오류
### 페이지
Github repo.의 README.md 이미지 업로드 오류 해결하기 
- [x] #5
- [x] WBS 이미지(1)
- [x] 개념, 논리, 물리 이미지(3)

**Comment by CJC0512** [comment]
이미지 업로드 확인했습니다.

**Comment by letsplaycoding** [comment]
사진 업로드 완료

**Comment by dongjunsong** [comment]
이미지 업로드 확인했습니다
