### ISSUE TITLE
README.md DDL 구문 변경#1

### ISSUE THREAD

**Issue by t4e1** [beyond-sw-camp/be04-1st-EarlyFar-FaaarCar#6]
# DDL 구문 수정 

- [x] Coupon 테이블 생성 구문 수정 
- [x] Accident 테이블 생성 구문 삭제 / 관련 테이블 FK 삭제 
- [x] User 테이블명 Member로 변경

**Comment by letsplaycoding** [comment]
구문 변경하신 거 확인했습니다.
