### ISSUE TITLE
README.md 토글 수정하기

### ISSUE THREAD

**Issue by joonangler** [beyond-sw-camp/be04-1st-EarlyFar-FaaarCar#7]
# README.md 토글 수정하기

 github repo.의 README.md 토글 수정하기
- [x] 요구사항 명세서
- [x] DDL
- [x] ~Test Case~
- [x] Test Case 각 항목별 토글 추가

**Comment by CJC0512** [comment]
DDL 토글 수정 완료.

**Comment by CJC0512** [comment]
DDL 토글 수정 완료
Test Case 토글 취소.

**Comment by letsplaycoding** [comment]
DDL 토글 수정하신 거 확인했습니다.

**Comment by CJC0512** [comment]
테스트 케이스 각 항목별 토글 추가로 인한 reopen입니다. issue도 수정하겠습니다.
