### ISSUE TITLE
데이터 모델링 - 로그인 내역 엔터티 인스턴스 중 '시도위치' -> '시도 경로' 변경

### ISSUE THREAD

**Issue by t4e1** [beyond-sw-camp/be04-1st-EarlyFar-FaaarCar#9]
# 로그인 내역 엔터티 인스턴스 중 '시도위치' -> '시도 경로'로 변경

- [x] 인스턴스명 수정 ( DDL ) 
- [x] DA# 논리모델 수정 
- [x] DA# 이미지 최신화

**Comment by letsplaycoding** [comment]
인스턴스명 변경 확인했습니다.
